### ISSUE TITLE
Displayed speed slider value is one off from set value when reopening options menu

### ISSUE THREAD

**Issue by jmolloy19** [AdvancedXRay/Auto-Clicker-Fabric#28]
**Describe the bug**
When opening the options menu and using the slider to set a tick speed, the text within the slider will display/confirm a selected tick speed. When closing the options menu and re-opening, the displayed tick speed within the slider is one off from previously displayed/set tick speed.

**To Reproduce**
1. Open options menu, and set any speed slider to 35 ticks as displayed set value.
2. Close options menu, and reopen options menu to view speed slider displaying a value of 34 ticks.

**Expected behavior**
Expect the displayed set value in slider to persist on closing and re-opening options menu.

**Screenshots**
Setting all speed sliders to 35 ticks

![image](https://user-images.githubusercontent.com/27863265/216867497-f4d99473-9dd8-4357-888d-d3d60fa1c68b.png)

Closing and reopening options menu

![image](https://user-images.githubusercontent.com/27863265/216867594-72e7ffb1-9c61-4943-8d28-4b0fbf098140.png)

**Minecraft Enviorment**
 - Minecraft Version: 1.19.3
 - XRay Mod Version: 1.5.0
 - Fabric Version: fabric-api-0.72.0+1.19.3

**Additional context**
The issue seems to happen only for certain odd integer values, and when it does happen, the error is consistently one less than actual selected value.

**Comment by MichaelHillcox** [comment]
Merged into 1.19.3 and 1.19.4, let me know if you want it to target any other versions
