### ISSUE TITLE
Inventory open issue

### ISSUE THREAD

**Issue by Fooftilly** [AdvancedXRay/Auto-Clicker-Fabric#3]
**Is your feature request related to a problem? Please describe.**
You can't have inventory open when the auto clicker is enabled.

**Describe the solution you'd like**
The solution should be implemented like auto fish mod or TbscCliker use where the clicker is active even if the inventory is open.

**Comment by MichaelHillcox** [comment]
Can I ask what the use case of this is? I'm happy to figure it out but I'm not sure what you'd use it for?

**Comment by MichaelHillcox** [comment]
No reason provided
