### ISSUE TITLE
1.20.2 support

### ISSUE THREAD

**Issue by mharbb** [AdvancedXRay/Auto-Clicker-Fabric#40]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mharbb** [comment]
self explanatory gui grashes when trying to open in 1.20.2

**Comment by MichaelHillcox** [comment]
Maybe wait until I've ported it? Might help...

**Comment by mharbb** [comment]
> Maybe wait until I've ported it? Might help...

still waiting

**Comment by MichaelHillcox** [comment]
Just gunna add another week onto the timeline seeing as you seem to think that I don't have a life and I have nothing better to do that port a small Minecraft mod...

**Comment by mharbb** [comment]
> Just gunna add another week onto the timeline seeing as you seem to think that I don't have a life and I have nothing better to do that port a small Minecraft mod...

alright can I just port it
