### ISSUE TITLE
[Bug]: Breaks blocks when spamming is set to true

### ISSUE THREAD

**Issue by IFedor-F** [AdvancedXRay/Auto-Clicker-Fabric#45]
**Describe the bug**
The autoclicker breaks blocks when spamming is set to true

**To Reproduce**
1. Set the settings like this
![image](https://github.com/AdvancedXRay/Auto-Clicker-Fabric/assets/116349244/ff83ecaa-5112-48bf-88fe-6f356c641c37)
2. Start attacking the block, it will slowly break with each hit and will break soon

**Expected behavior**
After each hit, the progress of breaking the block is reset

**Screenshots**
![image](https://github.com/AdvancedXRay/Auto-Clicker-Fabric/assets/116349244/84cbe7c0-8b0e-4eae-94a8-b847b2f84f3d)

**Minecraft Enviorment**
 - Minecraft Version: 1.20.4
 - XRay Mod Version: 84.0.0
 - Fabric Loader Version: 0.15.6
 - Fabric Api Version: 0.95.0+1.20.4

**Comment by MichaelHillcox** [comment]
This is minecraft behaviour not mine, I can't do anything about this, sorry.
